apiVersion: apps/v1
kind: Deployment
metadata:
  name: agrosupport-deployment
  labels:
    app: agrosupport
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agrosupport
  template:
    metadata:
      labels:
        app: agrosupport
    spec:
      containers:
        - name: agrosupport
          image: 083618020834.dkr.ecr.us-east-2.amazonaws.com/agrosupport:${IMAGE_TAG}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: agrosupport-config
          env:
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
