name: CD to Production

on:
  push:
    branches: [main]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to Render (Production)
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_PROD }}